//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FarmerSchemeSellAndBidding.Models
{
    using System;
    using System.Collections.Generic;
    using System.Runtime.Serialization;

    [DataContract]
    public partial class BankDetail
    {
        [DataMember]
        public int BankId { get; set; }
        [DataMember]
        public string IFSCCode { get; set; }
        [DataMember]
        public Nullable<long> BankAccountNo { get; set; }
        [DataMember]
        public Nullable<int> UserID { get; set; }
    
        public virtual RollType RollType { get; set; }
    }
}
