//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FarmerSchemeSellAndBidding.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BiddingTable
    {
        public int BidID { get; set; }
        public Nullable<int> bidAmount { get; set; }
        public Nullable<int> FarmerSellID { get; set; }
        public Nullable<bool> ApprovedBid { get; set; }
        public Nullable<System.DateTime> date { get; set; }
        public int UserID { get; set; }
        public Nullable<System.DateTime> Biddingdate { get; set; }
    
        public virtual FarmerCropdetil FarmerCropdetil { get; set; }
        public virtual RollType RollType { get; set; }
    }
}
