//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FarmerSchemeSellAndBidding.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClaimForm
    {
        public Nullable<int> PolicyNo { get; set; }
        public long ClaimNo { get; set; }
        public Nullable<System.DateTime> dateOfLoss { get; set; }
        public string CauseOfLoss { get; set; }
        public Nullable<bool> ClaimApprove { get; set; }
    
        public virtual InsuranceApplication InsuranceApplication { get; set; }
    }
}
