//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FarmerSchemeSellAndBidding.Models
{
    using System;
    using System.Collections.Generic;
    using System.Runtime.Serialization;
    [DataContract]
    public partial class FarmerLand
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public FarmerLand()
        {
            this.InsuranceApplications = new HashSet<InsuranceApplication>();
        }
        [DataMember]
        public int FarmId { get; set; }
        [DataMember]
        public string landArea { get; set; }
        [DataMember]
        public string landAddress { get; set; }
        [DataMember]
        public Nullable<int> landPinCode { get; set; }
        [DataMember]
        public Nullable<int> UserID { get; set; }
    
        public virtual RollType RollType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InsuranceApplication> InsuranceApplications { get; set; }
    }
}
