//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FarmerSchemeSellAndBidding.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class InsuranceApplication
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public InsuranceApplication()
        {
            this.ClaimForms = new HashSet<ClaimForm>();
        }
    
        public int PolicyNo { get; set; }
        public string season { get; set; }
        public int year { get; set; }
        public string cropname { get; set; }
        public Nullable<int> SumInsured { get; set; }
        public Nullable<int> FarmId { get; set; }
        public Nullable<int> UserID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ClaimForm> ClaimForms { get; set; }
        public virtual FarmerLand FarmerLand { get; set; }
        public virtual RollType RollType { get; set; }
    }
}
